### ISSUE TITLE
vim-ipython in cygwin

### ISSUE THREAD

**Issue by lucasfariaslf** [ivanov/vim-ipython#156] opened 2017-04-26 21:39 UTC
I'm trying to use vim-ipython under cygwin, IPython works outside vim, and I believe I have all necessary libs. I wonder if the error message could help you guys help me.

I first create and example .py: `vim test.py`. Once inside vim I call `:IPython`, which yields:

```
/usr/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should impo
rt from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/usr/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You sho
uld import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas.farias/.vim/plugged/vim-ipython/ftplugin/python/vim_ipython.py", line 151, in km_from_string
    km.load_connection_file()
  File "/usr/lib/python2.7/site-packages/jupyter_client/connect.py", line 450, in load_connection_file
    info = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ivanov** [comment] 2017-05-10 16:23
Sorry you're having trouble with vim-ipython. This sounds like a duplicate of #113.

Do you have an ipython kernel running? vim-ipython does not currently start a new kernel, it can only connect to kernels that have already been started via either ipython kernel or ipython console or by opening up a notebook file in jupyter.

**Comment by lucasfariaslf** [comment] 2017-07-11 22:23
Yeah, opening a jupiter console solved it. Thanks.

**Comment by ivanov** [comment] 2017-07-12 14:37
Glad to hear it! 👍

**Closed as completed by ivanov** 2017-07-12 14:37 UTC
